FROM golang:1.25-alpine3.22 AS builder

# Install npm and friends
RUN apk add npm nodejs make

# Install swaggo so that we could build OpenAPI documentation
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Install delve for debugging purposes
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Copy go.mod and go.sum so that we could cache dependencies
WORKDIR /app/backend
COPY go.mod go.sum ./

RUN go mod download && go mod verify

# Copy the rest of files
COPY . .

# Build the backend binary
RUN make debug

# Build OpenAPI documentation
RUN $(go env GOPATH)/bin/swag init -d ./cmd/pharmafinder,./

ENTRYPOINT [ "sh", "-c", "cp -r /app/backend/docs/* /app/docs && ./pharmafinder-dbg" ]
# For debugging with delve
# ENTRYPOINT [ "sh", "-c", "cp -r /app/backend/docs/* /app/docs && \$(go env GOPATH)/bin/dlv --listen=:4000 --headless=true --log=true --accept-multiclient --api-version=2 exec ./pharmafinder-dbg" ]